In [1]:
# Install dependencies if needed
# !pip install pandas scikit-learn nltk

import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("databricks-dolly-15k.csv")

# Preview
df.head()

,instruction,category,input,output
0,When did Virgin Australia start operating?,closed_qa,"Virgin Australia, the trading name of Virgin A...",Virgin Australia commenced services on 31 Augu...
1,Which is a species of fish? Tope or Rope,classification,NaN,Tope
2,Why can camels survive for long without water?,open_qa,NaN,Camels use the fat in their humps to keep them...
3,"Alice's parents have three daughters: Amy, Jes...",open_qa,NaN,The name of the third daughter is Alice
4,When was Tomoaki Komorida born?,closed_qa,Komorida was born in Kumamoto Prefecture on Ju...,"Tomoaki Komorida was born on July 10,1981."


In [5]:
print(df.columns.tolist())

['instruction', 'category', 'input', 'output']


In [6]:
import pandas as pd

df["text"] = (
    df.get("instruction", pd.Series("", index=df.index)).fillna('') + " " +
    df.get("input", pd.Series("", index=df.index)).fillna('') + " " +
    df.get("response", pd.Series("", index=df.index)).fillna('') + " " +
    df.get("output", pd.Series("", index=df.index)).fillna('')
)

In [10]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Load sample dataset
data = load_iris()

X = data.data   # features
y = data.target # labels

# Now split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Success!")

Success!


In [12]:
print(type(X_train[0]))

<class 'numpy.ndarray'>


In [16]:
print(type(X_train))
print(X_train[:3])

<class 'numpy.ndarray'>
[[4.4 2.9 1.4 0.2]
 [4.9 2.5 4.5 1.7]
 [6.8 2.8 4.8 1.4]]


In [18]:
print(dir())

['DecisionTreeClassifier', 'In', 'Out', 'RandomForestClassifier', 'TfidfVectorizer', 'X', 'X_test', 'X_train', '_', '_1', '__', '___', '__builtin__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__session__', '__spec__', '_dh', '_i', '_i1', '_i10', '_i11', '_i12', '_i13', '_i14', '_i15', '_i16', '_i17', '_i18', '_i2', '_i3', '_i4', '_i5', '_i6', '_i7', '_i8', '_i9', '_ih', '_ii', '_iii', '_oh', 'accuracy_score', 'classification_report', 'data', 'df', 'dt_model', 'exit', 'get_ipython', 'load_iris', 'np', 'open', 'pd', 'quit', 'rf_model', 'train_test_split', 'vectorizer', 'y', 'y_test', 'y_train']


In [20]:
# Train models (if not already done)
dt_model.fit(X_train, y_train)
rf_model.fit(X_train, y_train)

# Generate predictions
y_pred_dt = dt_model.predict(X_test)
y_pred_rf = rf_model.predict(X_test)

# Now create results DataFrame
results = pd.DataFrame({
    "Model": ["Decision Tree", "Random Forest"],
    "Accuracy": [
        accuracy_score(y_test, y_pred_dt),
        accuracy_score(y_test, y_pred_rf)
    ]
})

print(results)

           Model  Accuracy
0  Decision Tree  0.933333
1  Random Forest  0.900000


In [24]:
print(type(X_train))
print(type(X_train[0]))
print(X_train[0])

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[4.4 2.9 1.4 0.2]
